# Copyright (c) 2023 EPAM Systems, Inc.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

policies:
  - name: ecc-aws-485-codedeploy_ec2_minimum_healthy_hosts_configured
    comment: '010031132010'
    description: |
      CodeDeploy deployment groups for EC2 are not configured with a minimum healthy hosts 
    resource: aws.codedeploy-group
    filters:
      - type: value
        key: computePlatform
        value: Server
      - or:
          - and:
              - type: deployment-config-filter
                key: minimumHealthyHosts.type
                value: "FLEET_PERCENT"
              - type: deployment-config-filter
                key: minimumHealthyHosts.value
                op: lt
                value: 66
          - and:
              - type: deployment-config-filter
                key: minimumHealthyHosts.type
                value: "HOST_COUNT"
              - type: deployment-config-filter
                key: minimumHealthyHosts.value
                op: lt
                value: 1
