name: "Publish logs to S3"
description: "Publish logs to S3"
inputs:
  local_path:
    required: true
  remote_path:
    required: true

runs:
  using: "composite"
  steps: 
    - shell: bash
      run: |
          aws s3 cp ${{ inputs.local_path }} s3://${TF_BACKEND_STORAGE_NAME}/${{ inputs.remote_path }} --recursive
