# Copyright (c) 2023 EPAM Systems, Inc.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


policies:
  - name: ecc-aws-460-lambda_environment_variables_encrypted_in_transit
    comment: '010044030400'
    description: |
      Lambda environment variables are not encrypted in transit
    resource: aws.lambda
    filters:
      - type: value
        key: Environment
        value: present
      - type: value
        key: length(Environment.Variables.values(@) | [?!contains(@, 'AQICAH')]) > `0`
        value: true
