# Copyright (c) 2023 EPAM Systems, Inc.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


policies:
  - name: ecc-aws-038-security_group_ingress_is_restricted_traffic_to_smtp_port_25
    resource: aws.security-group
    description: |
      Security group rule allows internet traffic to SMTP port (25)
    filters:
      - type: ingress
        Ports: [25]
        Cidr:
          value:
            - "0.0.0.0/0"
          op: in
