# Copyright (c) 2023 EPAM Systems, Inc.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


policies:
  - name: ecc-aws-210-rds_instance_iam_authentication_configured
    resource: aws.rds
    description: |
      IAM authentication is not configured for RDS instances
    filters:
      - type: value
        key: IAMDatabaseAuthenticationEnabled
        value: false
    comment: '0034062000'