# Copyright (c) 2023 EPAM Systems, Inc.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


policies:
  - name: ecc-aws-062-security_group_ingress_is_restricted_22
    comment: '010042020300'
    description: |
      Security groups allow ingress from 0.0.0.0/0 or ::/0 to remote server administration port (22)
    resource: aws.security-group
    filters:
      - or:
          - type: ingress
            Ports: [22]
            Cidr:
              value:
                - "0.0.0.0/0"
              op: in
          - type: ingress
            Ports: [22]
            CidrV6:
              value:
                - "::/0"
              op: in
