# Copyright (c) 2023 EPAM Systems, Inc.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


policies:
  - name: ecc-aws-027-prevent_0-65535_ingress_and_all
    comment: '010042022000'
    description: |
      Security groups allows inbound access to all ports
    resource: aws.security-group
    filters:
      - type: value
        key: IpPermissions[?( (ToPort==`65535` && FromPort==`0`) || IpProtocol=='-1')]
        value_type: size
        op: gt
        value: 0
