# Copyright (c) 2023 EPAM Systems, Inc.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

policies:
  - name: ecc-aws-095-aws_config_configuration_changes_alarm_exists
    comment: '010016012900'
    description: |
      Log metric filter and alarm do not exist for AWS Config configuration changes
    resource: aws.account
    filters:
      - type: check-cloudtrail
        multi-region: true
        running: true
        include-management-events: true
        log-metric-filter-pattern:
            type: value
            op: regex
            value: '{ ?\(? ?\$\.eventSource ?= ?\"?config\.amazonaws\.com\"? ?\)? ?&& ?\( ?\(? ?\$\.eventName ?= ?\"?StopConfigurationRecorder\"? ?\)? ?\|\| ?\(? ?\$\.eventName ?= ?\"?DeleteDeliveryChannel\"? ?\)? ?\|\| ?\(? ?\$\.eventName ?= ?\"?PutDeliveryChannel\"? ?\)? ?\|\| ?\(? ?\$\.eventName ?= ?\"?PutConfigurationRecorder\"? ?\)? ?\) ?}'

