# Copyright (c) 2023 EPAM Systems, Inc.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


policies:
  - name: ecc-aws-142-s3_buckets_configured_with_block_public_access
    comment: '010040040301'
    description: |
      S3 Buckets are not configured with 'Block public access' bucket settings
    resource: aws.s3
    filters:
      - type: check-public-block
