# Copyright (c) 2023 EPAM Systems, Inc.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


policies:
  - name: ecc-aws-520-autoscaling_launch_config_hop_limit
    resource: launch-config
    description: |
      Auto Scaling launch configuration hop limit is greater than 1
    filters:
      - type: value
        key: MetadataOptions.HttpPutResponseHopLimit
        op: gt
        value: 1