# Copyright (c) 2023 EPAM Systems, Inc.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


policies:
  - name: ecc-aws-536-lambda_function_settings_check
    comment: '010028030400'
    description: |
      Lambda functions should not use deprecated runtimes
    resource: aws.lambda
    filters:
      - type: value
        key: PackageType
        value: Zip
      - not:
          - type: value
            key: Runtime
            op: in
            value: [nodejs22.x, nodejs20.x, nodejs18.x, python3.13, python3.12, python3.11, python3.10, python3.9, java21, java17, java11, java8.al2, dotnet9, dotnet8, dotnet6, ruby3.4, ruby3.3, ruby3.2, provided.al2023, provided.al2]
