# Copyright (c) 2023 EPAM Systems, Inc.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


policies:
  - name: ecc-aws-089-codebuild_environment_variables_contain_text_credentials
    description: |
      CodeBuild project environment variables contain clear text credentials
    resource: codebuild
    filters:
      - or:
          - type: value
            key: environment.environmentVariables[].name
            value_type: swap
            value: AWS_ACCESS_KEY_ID
            op: in
          - type: value
            key: environment.environmentVariables[].name
            value_type: swap
            value: AWS_SECRET_ACCESS_KEY
            op: in
    comment: '0048132200'