# Copyright (c) 2023 EPAM Systems, Inc.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


policies:
  - name: ecc-aws-322-api_gateway_rest_api_stages_ssl_certificates_configured
    description: |
      API Gateway REST API stages are not configured to use SSL certificates for backend authentication
    resource: rest-stage
    filters:
      - type: value
        key: clientCertificateId
        value: absent