# Copyright (c) 2023 EPAM Systems, Inc.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


policies:
  - name: ecc-aws-312-security_group_ingress_is_restricted_traffic_to_mssql_ports
    resource: aws.security-group
    description: |
      Security groups allow unrestricted access to MSSQL ports 1433, 1434
    filters:
      - type: ingress
        Ports: [1433, 1434]
        Cidr:
          value:
            - "0.0.0.0/0"
          op: in