# Copyright (c) 2023 EPAM Systems, Inc.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


policies:
  - name: ecc-aws-030-security_group_ingress_is_restricted_traffic_to_http_port_80
    comment: '010042022000'
    description: |
      Security group rule allows internet traffic to HTTP port (80)
    resource: aws.security-group
    filters:
      - type: ingress
        Ports: [80]
        Cidr:
          value:
            - "0.0.0.0/0"
          op: in
