# Copyright (c) 2023 EPAM Systems, Inc.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


policies:
  - name: ecc-aws-059-config_enabled_all_regions
    resource: account
    description: |
      AWS Config is not enabled in all regions
    filters:
      - type: check-config
        running: true
        all-resources: true
        global-resources: true
        
