# Copyright (c) 2023 EPAM Systems, Inc.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


policies:
  - name: ecc-aws-033-security_group_ingress_is_restricted_traffic_to_mysql_db_port_3306
    comment: '010042022000'
    description: |
      Security group rule allows unrestricted inbound access to TCP MySQL DB port (3306)
    resource: aws.security-group
    filters:
    - or:
      - type: ingress
        Ports: [3306]
        IpProtocol: "tcp"
        Cidr:
          value: "0.0.0.0/0"
      - type: ingress
        Ports: [3306]
        IpProtocol: "-1"
        Cidr:
          value: "0.0.0.0/0"

      - type: ingress
        Ports: [3306]
        IpProtocol: "tcp"
        CidrV6:
          value: "::/0"
      - type: ingress
        Ports: [3306]
        IpProtocol: "-1"
        CidrV6:
          value: "::/0"