# Copyright (c) 2023 EPAM Systems, Inc.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


policies:
  - name: ecc-aws-180-cloudfront_origin_failover_configured
    description: |
      CloudFront distributions origin failover is not configured
    resource: distribution
    filters:
      - type: distribution-config
        key: OriginGroups.Quantity
        op: eq
        value: 0
    comment: '0050022001'